export const Strings = {
  common: {
    loading: 'Loading...',
    refresh: 'Refresh',
    checkStatus: 'Check Status',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    ok: 'OK',
  },
  home: {
    headerSubtitle: 'Bank-Grade Financial Infrastructure',
    walletBalance: 'Operational Liquidity',
    yourTerminals: 'Active Settlement Nodes',
    recentTransactions: 'Grid Ledger History',
    createPayment: 'Initialize Transaction',
    noTerminals: 'No settlement nodes found',
    noTerminalsSub: 'Institutional authorization required to activate nodes',
    noTransactions: 'No operations recorded',
    waitingAssignment: 'Node Registration Pending',
    waitingSubtitle: 'This hardware has been registered in the mainnet cluster. Contact your compliance officer for node activation.',
    stillWaiting: 'Awaiting Authorization',
  },
  login: {
    subtitle: 'Node Authentication Required',
    email: 'Institutional Email',
    password: 'Vault Password',
    loginButton: 'Initialize Access',
    loginSuccess: 'Authentication successful',
    loginFailed: 'Authorization failed',
    fillFields: 'Identity credentials required',
  },
  history: {
    title: 'Audit Ledger',
    subtitle: 'High-fidelity settlement telemetry',
    empty: 'No clearing records identified',
    posSale: 'Institutional Sale',
  },
  settings: {
    title: 'Node Configuration',
    profile: 'Officer Profile',
    setPin: 'Configure Operator PIN',
    logout: 'De-authenticate Node',
    pinModalTitle: 'MFA Operator PIN',
    pinModalSubtitle: 'Establish an encrypted 4-digit PIN for rapid node access.',
    savePin: 'Commit PIN',
    pinLengthError: 'Encryption requires 4 digits',
    pinSuccess: 'MFA configuration updated',
    pinFailed: 'Commit failed',
  },
  pinLock: {
    title: 'Node Locked',
    subtitle: 'MFA Authentication Required',
    invalidPin: 'Verification failed',
    logout: 'ABORT SESSION',
  },
  transaction: {
    amount: 'Principal Amount',
    description: 'Order Reference',
    status: 'Clearing Status',
    date: 'Timestamp',
    paymentMethods: 'Settlement Channels',
    t0Settlement: 'Ultra T+0 Node',
    completePayment: 'Authorize Settlement',
    paidSuccessfully: 'FUNDS CLEARED',
    finish: 'Commit',
    completed: 'SETTLED',
    done: 'Cleared',
    cancel: 'Abort',
    selectOption: 'Select Clearing Path',
    debitCreditCard: 'Institutional Card Capture',
    payWith: 'Settle via',
    qrCode: 'Industrial QR Node',
    quickAccess: 'Rapid Ops',
    mayaQr: 'Maya Mainnet',
    qrph: 'BSP QRPH Grid',
    helpCenter: 'Compliance Desk',
    charge: 'AUTHORIZE',
  },
  guide: {
    activateTitle: 'Mainnet Cluster Deployment',
    activateText: 'To initialize industrial-scale settlement, inject institutional API keys into the production vault.',
    step1: 'Provision Maya Business Master Keys',
    step2: 'Sync Institutional Secrets to Railway Vault',
    step3: 'Initialize Mainnet Cluster Mode',
    viewSetup: 'Compliance Protocols',
  }
};
